name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Здесь укажите имя вашей основной ветки

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Укажите версию Python, если она необходима

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          cd /home/runner/mkdocs_project
          mkdocs build

      - name: Add ssh key
        run: | 
          set -eu
          mkdir "/home/runner/.ssh"
          echo "${{ secrets.SSH_KEY_CONNECTION }}" > "$HOME/.ssh/git_key"
          chmod 600 "/home/runner/.ssh/git_key"

      - name: Update host content   
        shell: bash
        env:
          USER: ${{ secrets.SSH_USER }}
          HOST: ${{ secrets.SSH_HOST }}
          DIST: ${{ secrets.DIST }}
        run: |
          rsync -e "ssh -i /home/runner/.ssh/git_key -o StrictHostKeyChecking=no $USER@$HOST " -avz /home/runner/mkdocs_project/site/*  $USER@$HOST:$DIST/site/

