name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material
      - name: Build documentation
        run: |
          cd docs-client
          mkdocs build
          cd $HOME/work/mkdocs_project/mkdocs_project/docs-client
          
      - name: Add ssh key
        run: | 
          set -eu
          mkdir "$HOME/.ssh"
          ls -la
          echo "${{ secrets.SSH_KEY_CONNECTION }}" > $HOME/.ssh/key
          chmod 600 $HOME/.ssh/key
          pwd

      - name: Update host content   
        shell: bash
        run: |
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" -avz docs-client/site/*  powerit@206.81.27.146:/home/powerit/mkdocs_project/site/
