name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Здесь укажите имя вашей основной ветки

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Укажите версию Python, если она необходима

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material  # Укажите необходимые зависимости

      - name: Build documentation
        run: |
          mkdocs build  # Команда для сборки документации
          scp -r site/* powerit@206.81.27.146:/home/powerit/mkdocs_project  # Перенос файлов на сервер

      - name: Add ssh key
        run: | 
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.ACTIONS_SSH_KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
